name = "GBPlotsInteractive"
uuid = "3bd7733c-6c6f-4d1a-b1c7-922c1077833d"
authors = ["jeffersonparil@gmail.com"]
version = "1.0.0-DEV"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GBCore = "50d95318-1838-4cfa-a614-3543b4bb0509"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[sources]
GBCore = {rev = "main", url = "https://github.com/GenomicBreeding/GBCore.jl"}

[compat]
ColorSchemes = "3.28.0"
DataFrames = "1.7.0"
Distributions = "0.25.117"
Documenter = "1.9.0"
GBCore = "1.0.0"
GLMakie = "0.11.2"
LinearAlgebra = "1.11.0"
MultivariateStats = "0.10.3"
StatsBase = "0.34.4"
UnicodePlots = "3.7.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
